version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

permissions:
  - object: /
    pattern: "**"
    owner: tomcat
    group: tomcat


hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: root
  ApplicationStart:
    - location: deploy.sh
      runas: root